### ISSUE TITLE
are there updates to the code for win prob and expected value?

### ISSUE THREAD

**Issue by elvismtw** [nekobean/mahjong-cpp#5]
When I give the same hand in https://pystyle.info/apps/mahjong-nanikiru-simulator and the C++ code, there're slight differences in win prob, tenpai probs, and expected value, which I think the result on the website is more accurate. I wanna ask if there is a new version of calculating these numbers or not.

**Comment by nekobean** [comment]
Calculations on the website are done with code in this repository.
I checked a few hands and the results are the same for the C++ code and the website.
If you perform calculations under the same conditions and get different results, could you tell me the hands?

**Comment by elvismtw** [comment]
Ah, I found out why.

I change the flag from 63 to 127 (which means adding flag 64), and the results become "almost the same". 
I wonder what is the effect of flag 64, as changing this parameter in the website only changes the output order according to win prob or expected value without changing any number. 
In the C++ code, I notice the tenpai probability and win probability have some negligible change (slight change after 12 decimal places), but the expected value increase by a few hundreds, which is why I said I can't get the same result yesterday.

Also, I might have found a bug. I think the remaining count of tile is assumed to be 4 for each tile and 1 for each type of red five.
But there are only 3 red five for each type. For example, in the ipynb in docs, the hand is
222567m34p33667s4z
and the count is 
[4,1,4,4, **3** ,3,3,4,4,4,4,3,3, **4** ,4,4,4,4,4,4,2,4, **4** ,2,3,4,4,3,4,4,3,4,4,4,1,1,1]
there should be only 2* 5m, 3* 5p, 3* 5s left because the 1, 1, 1 at the end already counts the red five and a 5m in the hand.

I do get the same result after adding an imaginary five of each type to count :)

**Comment by nekobean** [comment]
## Flag

Each flag has the following meaning

* flag 1: Allow to discard tile that increases syanten number. (向聴戻し)
* flag 2: Consider drawing the tile that does not change the syanten number. (手変わり)
* flag 4: Consider "Double Reach"  when scoring. (ダブル立直)
* flag 8:  Consider "First Turn Win"  when scoring. (一発)
* flag 16: Consider "Last tile from the wall"  when scoring. (海底撈月)
* flag 32: Consider "blind bonus tile"  when scoring. (裏ドラ)
* flag 64: Consider drawing the red tile. (赤牌自摸)
* flag 128: the policy for selecting the tiles to discard. (和了確率最大化)

Flag 128 determines the policy for selecting the tiles to discard.
If flag 128 is enabled, discard the tile that maximizes the win probability.
otherwise, discard the tile that maximizes the expected score value.

On the website,
* "Maximize Win Probability (和了確率最大化)" button is selected, flag 128 is enabled. The results are sorted in descending order of win probability.
* "Maximize Expected Score Value (期待値最大化)" button is selected, flag 128 is disabled. The results are sorted in descending order of expected score value.

## Array of Remaining Tiles

The last three elements are flags to indicate whether red tiles remain.

count[0] ~ count[33]: remaining number of tiles. (red tile included)
count[34]: flag red 5m remains.
count[35]: flag red 5p remains.
count[36]: flag red 5s remains.

`counts` array of 222567m34p33667s4z should be 
[4,1,4,4,3,3,3,4,4, 4,4,3,3,4,4,4,4,4, 4,4,2,4,4,2,3,4,4, 3,4,4,3,4,4,4, 1,1,1]
because all red tiles remains.

**Comment by elvismtw** [comment]
That's very clear. Thanks!
